logstash:
  image: docker.elastic.co/logstash/logstash:5.5.0
  volumes:
    - ./pipeline:/usr/share/logstash/pipeline/
    - ./config:/usr/share/logstash/config/
  ports:
    - "5000:5000"
    - "5000:5000/udp"
  environment:
    - ELASTICSEARCH_HOSTS=<es_host>
